"""Initial migration

Revision ID: dd6826528540
Revises: 
Create Date: 2026-09-29 07:30:00.645701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6826528540'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('delivered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('rtsp_url', sa.String(), nullable=False),
    sa.Column('live_path', sa.String(), nullable=False),
    sa.Column('analysis_fps', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_frame_at', sa.Integer(), nullable=True),
    sa.Column('reference_snapshot', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cls', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('first_seen', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.Column('sightings', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('tentative','confirmed')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','incharge')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('identity_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('top3_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_cameras',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'camera_id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('points_json', sa.String(), nullable=False),
    sa.Column('ignore_json', sa.String(), nullable=True),
    sa.CheckConstraint("type IN ('polygon','line')"),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registered_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('spec_json', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("severity IN ('low','medium','critical')"),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('details_json', sa.String(), nullable=True),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('new','acknowledged','false_alarm')"),
    sa.ForeignKeyConstraint(['action_id'], ['registered_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('start_ts', sa.Integer(), nullable=False),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pinned', sa.Integer(), nullable=True),
    sa.Column('retention_until', sa.Integer(), nullable=True),
    sa.Column('meta_path', sa.String(), nullable=True),
    sa.CheckConstraint("state IN ('recording','finalizing','ready','failed')"),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_table('events')
    op.drop_table('registered_actions')
    op.drop_table('zones')
    op.drop_table('user_cameras')
    op.drop_table('sightings')
    op.drop_table('identity_embeddings')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('incidents')
    op.drop_table('identities')
    op.drop_table('cameras')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    # ### end Alembic commands ###
